---
title: "simulate"
output: html_document
date: '2022-02-20'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pacman::p_load(tidyverse, tsibble, fable, feasts, janitor, lubridate, tseries, TTR, xts, tsbox, quantmod, gridExtra)
```

```{r, message=FALSE}
assets <- read_csv("assets.csv") %>% 
    select(date, bitcoin, rsi_btc, mean_rsi_btc, sd_rsi_btc, gold, rsi_gold, mean_rsi_gold, sd_rsi_gold) %>% 
    mutate(date = ymd(date))
```

```{r}
convert <- function(from, to, from_amt, on_hand, curr_val) {
    if (str_detect(str_to_lower(from), "btc|bitcoin")) {
        #Converting from Bitcoin
        if (str_detect(str_to_lower(to), "usd|cash")) {
            #Bitcoin to cash
            if(from_amt > on_hand) {    #Check we have enough money for the conversion
                stop("'from_amount' is more than on hand amount")
            }
            conv = (from_amt * curr_val) * 0.98 #Calculate conversion
            
            res = tribble(
                ~amt, ~on_hand,
                conv, on_hand - from_amt
            )
            
            return(res) #return the conversion and the amount of currency left over
            
        } else {
            stop("Conversion type 'to' is invalid")
        }
    } else if (str_detect(str_to_lower(from), "gold")) {
        #Converting from gold
        if (str_detect(str_to_lower(to), "usd|cash")) {
            #Gold to cash
            if(from_amt > on_hand) {    #Check we have enough money for the conversion
                stop("'from_amount' is more than on hand amount")
            }
            conv = (from_amt * curr_val) * 0.99 #Calculate conversion
            
             res = tribble(
                ~amt, ~on_hand,
                conv, on_hand - from_amt
            )
            
            return(res) #return the conversion and the amount of currency left over left over
            
        } else {
            stop("Conversion type 'to' is invalid")
        }
    } else if (str_detect(str_to_lower(from), "usd|cash")) {
        #Converting from USD
        if (str_detect(str_to_lower(to), "btc|bitcoin")) {
            #USD to bitcoin
            if(from_amt > on_hand) {    #Check we have enough money for the conversion
                stop("'from_amount' is more than on hand amount")
            }
            conv = (from_amt / curr_val) * 0.98 #Calculate conversion
            
             res = tribble(
                ~amt, ~on_hand,
                conv, on_hand - from_amt
            )
            
            return(res) #return the conversion and the amount of currency left over
            
        } else if (str_detect(str_to_lower(to), "gold")) {
            #USD to gold
            if(from_amt > on_hand) {    #Check we have enough money for the conversion
                stop("'from_amount' is more than on hand amount")
            }
            conv = (from_amt / curr_val) * 0.99 #Calculate conversion
            
             res = tribble(
                ~amt, ~on_hand,
                conv, on_hand - from_amt
            )
            
            return(res) #return the conversion and the amount of currency left over
        } else {
            stop("Conversion type 'to' is invalid")
        }
    } else {
        stop("Conversion type 'from' is invalid")
    }
}
```

```{r}
test <- convert("btc", "usd", 10, 100, 500)
test$amt
test$on_hand

```
```{r}
get_curr_val <- function(x, from) {
    if (str_detect(str_to_lower(to), "btc|bitcoin")) {
        return(x$bitcoin)
    }
    else if (str_detect(str_to_lower(to), "gold")) {
        return(x$gold)
    } else {stop("Invalid 'from' type")}
}
```



```{r}
choose_currency <- function(x, account_table) {
    #x is just a dataframe with only 1 row, col_names are same as piped in df
    #account_table is the new table storing currency amounts
    
    # Ex: assets %>% head(5) %>% rowwise() %>% choose_currency()
        # where choose_currency() has "print(x$bitcoin)" will result in:
        # [1] 621.65 609.67 610.92 608.82 610.38
    
    # 1) Put however you decide currency and amount right here
        from = "btc" # Assign to btc or usd or gold
        to = " gold" # ^
        from_amt = 1 #Assign to amount determined by score/method
        on_hand = lag(account_table[from], default = 0) #previous currency amount on hand
        curr_val = get_curr_val(x, from) #Get current value of 'from' type
            
    
    # 2) Convert, make sure we know where to put the data after conversion 
        profit = convert(from, to, from_amt, on_hand, curr_val)
        
    # 3) Add profit to our account table
        if (str_detect(str_to_lower(from), "btc|bitcoin")) {
            account_table <- account_table %>% 
                add_row(cash = lag(cash)+profit$amt, bitcoin = profit$on_hand)
            
        } else if(str_detect(str_to_lower(from), "gold")) {
            account_table <- account_table %>% 
                add_row(cash = lag(cash)+profit$amt, gold = profit$on_hand)
            
        } else if(str_detect(str_to_lower(from), "usd|cash")) {
            
            if(str_detect(str_to_lower(from), "btc|bitcoin")) {
                account_table <- account_table %>% 
                    add_row(bitcoin = lag(bitcoin)+profit$amt, usd = profit$on_hand)
                
            } else if(str_detect(str_to_lower(from), "gold")) {
                account_table <- account_table %>% 
                    add_row(gold = lag(gold)+profit$amt, usd = profit$on_hand)
            }
        }
        
        
}
```

